version: 2
updates:
  # Maintain dependencies for Pulpcore
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[dependabot]"
    # Add labels for dependabot bumps
    labels:
      - "dependabot"
    ignore:
      - dependency-name: "pulpcore"
        update-types: ["version-update:semver-major"]
